# Generated by Django 3.1.1 on 2020-09-21 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='保密', max_length=20, verbose_name='手机')),
                ('sex', models.CharField(choices=[('1', '男'), ('2', '女')], default=1, max_length=1, verbose_name='性别')),
                ('web', models.CharField(default='保密', max_length=50, verbose_name='个人网站')),
                ('aboutme', models.TextField(default='保密', max_length=200, verbose_name='个性签名')),
                ('photo', models.ImageField(default='photo/default.jpg', upload_to='photo/', verbose_name='头像')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户详细信息',
                'verbose_name_plural': '用户详细信息',
            },
        ),
    ]
