# Generated by Django 3.1.1 on 2020-09-27 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200924_1659'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_articleview'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleview',
            name='is_like',
            field=models.BooleanField(default=0, verbose_name='是否收藏'),
        ),
        migrations.AlterField(
            model_name='articleview',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.article', verbose_name='文章名'),
        ),
        migrations.AlterField(
            model_name='articleview',
            name='time',
            field=models.DateField(auto_now_add=True, verbose_name='浏览时间'),
        ),
        migrations.AlterField(
            model_name='articleview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
    ]
