# Generated by Django 3.1.1 on 2020-09-27 17:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20200924_1659'),
        ('account', '0003_auto_20200927_1725'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleView',
            new_name='ArticleViewHistory',
        ),
        migrations.AlterModelOptions(
            name='articleviewhistory',
            options={'ordering': ('-time',), 'verbose_name': '用户浏览文章记录', 'verbose_name_plural': '用户浏览文章记录'},
        ),
    ]
