# Generated by Django 3.1.1 on 2020-09-27 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200927_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleviewhistory',
            options={'ordering': ('-time',), 'verbose_name': '用户浏览记录', 'verbose_name_plural': '用户浏览记录'},
        ),
    ]
