# Generated by Django 3.1.1 on 2020-09-28 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0006_auto_20200927_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='留言内容')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='留言时间')),
                ('level', models.IntegerField(default=0, verbose_name='留言等级')),
                ('father', models.IntegerField(default=None, null=True, verbose_name='父留言')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '留言记录表',
                'verbose_name_plural': '留言记录表',
            },
        ),
    ]
