# Generated by Django 3.1.1 on 2020-09-30 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200924_1659'),
        ('account', '0012_auto_20200930_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmessage',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.article', verbose_name='文章'),
        ),
    ]
