# Generated by Django 3.1.1 on 2020-10-15 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20201010_1520'),
        ('account', '0013_commentmessage_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleviewhistory',
            name='article_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='分类名'),
        ),
        migrations.AlterField(
            model_name='articleviewhistory',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.article', verbose_name='文章名'),
        ),
        migrations.AlterField(
            model_name='articleviewhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
    ]
