# Generated by Django 3.1.1 on 2020-10-15 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20201015_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleviewhistory',
            old_name='article_category',
            new_name='category',
        ),
    ]
