# Generated by Django 3.1.1 on 2020-10-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20201015_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='web',
            field=models.CharField(default='#', max_length=50, verbose_name='个人网站'),
        ),
    ]
