# Generated by Django 3.1.3 on 2020-12-01 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0020_content_collection'),
        ('account', '0018_auto_20201109_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleviewhistory',
            options={'ordering': ('-time',), 'verbose_name': '博文浏览记录', 'verbose_name_plural': '博文浏览记录'},
        ),
        migrations.CreateModel(
            name='ContentViewHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='浏览时间')),
                ('is_like', models.BooleanField(default=0, verbose_name='是否收藏')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.content', verbose_name='笔记标题')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.note', verbose_name='所属笔记')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '笔记浏览记录',
                'verbose_name_plural': '笔记浏览记录',
                'ordering': ('-time',),
            },
        ),
    ]
