# Generated by Django 3.1.3 on 2020-12-01 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_auto_20201201_2134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleviewhistory',
            name='category',
        ),
    ]
