# Generated by Django 3.1.3 on 2020-12-02 14:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20201202_1352'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0021_auto_20201202_1146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoteMessage',
            new_name='SectionMessage',
        ),
    ]
