# Generated by Django 3.1.3 on 2020-12-02 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_auto_20201202_1400'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionmessage',
            old_name='note',
            new_name='section',
        ),
    ]
