# Generated by Django 3.1.3 on 2020-12-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20201202_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='web',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='个人网站'),
        ),
    ]
