# Generated by Django 3.1.3 on 2020-12-20 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20201219_1601'),
        ('account', '0026_auto_20201220_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionviewhistory',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.note', verbose_name='所属笔记'),
        ),
    ]
