# Generated by Django 3.1.1 on 2020-09-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='carousel/', verbose_name='轮播图')),
                ('url', models.URLField(max_length=100, verbose_name='图片链接')),
                ('info', models.CharField(default='', max_length=50, verbose_name='图片标题')),
            ],
            options={
                'verbose_name': '轮播图',
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='网站图标')),
                ('name', models.CharField(max_length=20, verbose_name='链接名称')),
                ('url', models.URLField(max_length=100, verbose_name='网址')),
                ('describe', models.CharField(default='', max_length=50, verbose_name='图片标题')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
            },
        ),
    ]
