# Generated by Django 3.1.1 on 2020-09-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
    ]
