# Generated by Django 3.1.1 on 2020-10-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20201021_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websiteconfig',
            name='copyright',
            field=models.CharField(max_length=100, verbose_name='版权信息'),
        ),
    ]
