# Generated by Django 3.1.1 on 2020-10-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_auto_20201021_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foreground', models.ImageField(default='images/logo_forground.png', upload_to='images/', verbose_name='前台logo')),
                ('background', models.ImageField(default='images/logo_background.png', upload_to='images/', verbose_name='后台logo')),
                ('icon', models.ImageField(default='images/favicon.ico', upload_to='images/', verbose_name='icon')),
                ('photo', models.ImageField(default='images/photo.jpg', upload_to='images/', verbose_name='默认头像')),
                ('cover', models.ImageField(default='images/cover.jpg', upload_to='images/', verbose_name='默认封面')),
                ('pay', models.ImageField(default='images/pay.png', upload_to='images/', verbose_name='赞赏二维码')),
            ],
            options={
                'verbose_name': '网站配置',
                'verbose_name_plural': '网站配置',
            },
        ),
        migrations.AddField(
            model_name='bloggerinfo',
            name='qq',
            field=models.ImageField(default='images/qq.png', upload_to='images/', verbose_name='qq二维码'),
        ),
        migrations.AddField(
            model_name='bloggerinfo',
            name='weixin',
            field=models.ImageField(default='images/weixin.png', upload_to='images/', verbose_name='微信二维码'),
        ),
    ]
