# Generated by Django 3.1.2 on 2020-10-22 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_auto_20201022_1259'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BloggerInfo',
            new_name='Info',
        ),
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': '关于页面', 'verbose_name_plural': '关于页面'},
        ),
        migrations.AlterModelOptions(
            name='imagesconfig',
            options={'verbose_name': '图片配置', 'verbose_name_plural': '图片配置'},
        ),
        migrations.AlterField(
            model_name='websiteconfig',
            name='descript',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='META描述'),
        ),
        migrations.AlterField(
            model_name='websiteconfig',
            name='keywords',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='META关键词'),
        ),
    ]
