# Generated by Django 3.1.2 on 2020-10-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20201022_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='is_show',
            field=models.BooleanField(default=True, verbose_name='是否显示'),
        ),
    ]
