# Generated by Django 3.1.2 on 2020-10-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_carousel_is_show'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name': '轮播图管理', 'verbose_name_plural': '轮播图管理'},
        ),
        migrations.AddField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('1', '友情链接'), ('2', '热门推荐')], default=1, max_length=1, verbose_name='性别'),
        ),
    ]
