# Generated by Django 3.1.2 on 2020-11-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_auto_20201023_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.CharField(choices=[('1', '友情链接'), ('2', '强烈推荐')], default=1, max_length=1, verbose_name='类型'),
        ),
    ]
