# Generated by Django 3.1.2 on 2020-11-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20201101_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='url',
            field=models.URLField(max_length=300, verbose_name='图片链接'),
        ),
    ]
