# Generated by Django 3.1.1 on 2020-09-30 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200924_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment',
            field=models.PositiveIntegerField(default=0, verbose_name='评论数'),
        ),
    ]
