# Generated by Django 3.1.1 on 2020-10-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_is_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='recommend',
        ),
        migrations.AddField(
            model_name='article',
            name='is_recommend',
            field=models.BooleanField(default=False, verbose_name='是否推荐显示'),
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, default='cover/default.jpg', null=True, upload_to='cover/', verbose_name='文章图片'),
        ),
    ]
