# Generated by Django 3.1.3 on 2020-11-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='url',
            field=models.CharField(max_length=300, verbose_name='笔记链接'),
        ),
    ]
