# Generated by Django 3.1.3 on 2020-11-22 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201120_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='url',
        ),
    ]
