# Generated by Django 3.1.3 on 2020-11-22 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0010_remove_note_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='笔记标题')),
                ('body', mdeditor.fields.MDTextField()),
                ('view', models.PositiveIntegerField(default=0, verbose_name='阅读量')),
                ('like', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('comment', models.PositiveIntegerField(default=0, verbose_name='评论数')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('is_release', models.BooleanField(default=True, verbose_name='是否发布')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '笔记内容',
                'verbose_name_plural': '笔记内容',
            },
        ),
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('level', models.IntegerField(max_length=2, verbose_name='级别')),
                ('father', models.IntegerField(max_length=4, verbose_name='父目录ID')),
                ('order', models.IntegerField(max_length=4, verbose_name='顺序')),
                ('is_unfold', models.BooleanField(default=False, verbose_name='是否展开')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.content', verbose_name='笔记内容')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.note', verbose_name='笔记名称')),
            ],
            options={
                'verbose_name': '文章目录',
                'verbose_name_plural': '文章目录',
            },
        ),
    ]
