# Generated by Django 3.1.3 on 2020-11-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_catalogue_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogue',
            name='father',
            field=models.IntegerField(verbose_name='父目录ID'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='level',
            field=models.IntegerField(verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='order',
            field=models.IntegerField(verbose_name='顺序'),
        ),
    ]
