# Generated by Django 3.1.3 on 2020-11-23 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20201122_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firstcatalogue',
            options={'ordering': ('order',), 'verbose_name': '笔记一级目录', 'verbose_name_plural': '笔记一级目录'},
        ),
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.content', verbose_name='笔记内容'),
            preserve_default=False,
        ),
    ]
