# Generated by Django 3.1.3 on 2020-11-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20201123_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_release',
            field=models.BooleanField(default=True, verbose_name='是否发布'),
        ),
    ]
