# Generated by Django 3.1.3 on 2020-11-23 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_note_is_release'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='is_release',
        ),
    ]
