# Generated by Django 3.1.3 on 2020-12-02 13:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0021_auto_20201202_1146'),
        ('blog', '0020_content_collection'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content',
            new_name='Section',
        ),
    ]
