# Generated by Django 3.1.3 on 2020-12-06 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20201202_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='标题名称')),
                ('order', models.IntegerField(verbose_name='序号')),
                ('level', models.IntegerField(verbose_name='等级')),
                ('father', models.IntegerField(blank=True, null=True, verbose_name='父目录ID')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.note', verbose_name='笔记名称')),
            ],
            options={
                'verbose_name': '笔记目录',
                'verbose_name_plural': '笔记目录',
                'ordering': ('level', 'order'),
            },
        ),
        migrations.RemoveField(
            model_name='secondcatalogue',
            name='content',
        ),
        migrations.RemoveField(
            model_name='secondcatalogue',
            name='father',
        ),
        migrations.DeleteModel(
            name='FirstCatalogue',
        ),
        migrations.DeleteModel(
            name='SecondCatalogue',
        ),
    ]
