# Generated by Django 3.1.3 on 2020-12-06 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20201206_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='blog.section', verbose_name='笔记内容'),
        ),
    ]
