# Generated by Django 3.1.3 on 2020-12-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_catalogue_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogue',
            options={'ordering': ('father', 'order'), 'verbose_name': '笔记目录', 'verbose_name_plural': '笔记目录'},
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='level',
            field=models.IntegerField(default=2, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='order',
            field=models.IntegerField(default=1, verbose_name='序号'),
        ),
    ]
